[install.scopes]
"@fortawesome" = {url = "https://npm.fontawesome.com/:_authToken=$FONTAWESOME_NPM_AUTH_TOKEN"}
"@awesome.me" = {url = "https://npm.fontawesome.com/:_authToken=$FONTAWESOME_NPM_AUTH_TOKEN"}
